/// <reference types="next" />
/// <reference types="next/image-types/global" />

<<<<<<< HEAD
// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/building-your-application/configuring/typescript for more information.
=======
// This file is auto-generated by Next.js and should not be edited.
>>>>>>> 9b3ea71a9b92e027eabc184f84a67383cf133a2c
